package cn.soft.news.po;

import java.io.Serializable;
import java.util.Date;

/**
 * @author Hanoch
 */
public class TbNews implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.news_id
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private String newsId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.news_theme_id
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private Integer newsThemeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.news_author
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private String newsAuthor;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.news_title
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private String newsTitle;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.news_up
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private Long newsUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.news_down
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private Long newsDown;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.news_create_time
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private Date newsCreateTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_news.news_content
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private String newsContent;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.news_id
     *
     * @return the value of tb_news.news_id
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public String getNewsId() {
        return newsId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.news_id
     *
     * @param newsId the value for tb_news.news_id
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setNewsId(String newsId) {
        this.newsId = newsId == null ? null : newsId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.news_theme_id
     *
     * @return the value of tb_news.news_theme_id
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public Integer getNewsThemeId() {
        return newsThemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.news_theme_id
     *
     * @param newsThemeId the value for tb_news.news_theme_id
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setNewsThemeId(Integer newsThemeId) {
        this.newsThemeId = newsThemeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.news_author
     *
     * @return the value of tb_news.news_author
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public String getNewsAuthor() {
        return newsAuthor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.news_author
     *
     * @param newsAuthor the value for tb_news.news_author
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setNewsAuthor(String newsAuthor) {
        this.newsAuthor = newsAuthor == null ? null : newsAuthor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.news_title
     *
     * @return the value of tb_news.news_title
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public String getNewsTitle() {
        return newsTitle;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.news_title
     *
     * @param newsTitle the value for tb_news.news_title
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setNewsTitle(String newsTitle) {
        this.newsTitle = newsTitle == null ? null : newsTitle.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.news_up
     *
     * @return the value of tb_news.news_up
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public Long getNewsUp() {
        return newsUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.news_up
     *
     * @param newsUp the value for tb_news.news_up
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setNewsUp(Long newsUp) {
        this.newsUp = newsUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.news_down
     *
     * @return the value of tb_news.news_down
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public Long getNewsDown() {
        return newsDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.news_down
     *
     * @param newsDown the value for tb_news.news_down
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setNewsDown(Long newsDown) {
        this.newsDown = newsDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.news_create_time
     *
     * @return the value of tb_news.news_create_time
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public Date getNewsCreateTime() {
        return newsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.news_create_time
     *
     * @param newsCreateTime the value for tb_news.news_create_time
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setNewsCreateTime(Date newsCreateTime) {
        this.newsCreateTime = newsCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_news.news_content
     *
     * @return the value of tb_news.news_content
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public String getNewsContent() {
        return newsContent;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_news.news_content
     *
     * @param newsContent the value for tb_news.news_content
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setNewsContent(String newsContent) {
        this.newsContent = newsContent == null ? null : newsContent.trim();
    }

    @Override
    public String toString() {
        return "TbNews{" +
                "newsId='" + newsId + '\'' +
                ", newsThemeId=" + newsThemeId +
                ", newsAuthor='" + newsAuthor + '\'' +
                ", newsTitle='" + newsTitle + '\'' +
                ", newsUp=" + newsUp +
                ", newsDown=" + newsDown +
                ", newsCreateTime=" + newsCreateTime +
                ", newsContent='" + newsContent + '\'' +
                '}';
    }
}