package cn.soft.news.po;

import java.io.Serializable;
import java.util.Date;

/**
 * @author Hanoch
 */
public class TbTheme implements Serializable {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_theme.theme_id
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private Integer themeId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_theme.theme_name
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private String themeName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_theme.theme_detail
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private String themeDetail;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_theme.theme_level
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private Integer themeLevel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column tb_theme.theme_create_time
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    private Date themeCreateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_theme.theme_id
     *
     * @return the value of tb_theme.theme_id
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public Integer getThemeId() {
        return themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_theme.theme_id
     *
     * @param themeId the value for tb_theme.theme_id
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setThemeId(Integer themeId) {
        this.themeId = themeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_theme.theme_name
     *
     * @return the value of tb_theme.theme_name
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public String getThemeName() {
        return themeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_theme.theme_name
     *
     * @param themeName the value for tb_theme.theme_name
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setThemeName(String themeName) {
        this.themeName = themeName == null ? null : themeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_theme.theme_detail
     *
     * @return the value of tb_theme.theme_detail
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public String getThemeDetail() {
        return themeDetail;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_theme.theme_detail
     *
     * @param themeDetail the value for tb_theme.theme_detail
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setThemeDetail(String themeDetail) {
        this.themeDetail = themeDetail == null ? null : themeDetail.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_theme.theme_level
     *
     * @return the value of tb_theme.theme_level
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public Integer getThemeLevel() {
        return themeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_theme.theme_level
     *
     * @param themeLevel the value for tb_theme.theme_level
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setThemeLevel(Integer themeLevel) {
        this.themeLevel = themeLevel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column tb_theme.theme_create_time
     *
     * @return the value of tb_theme.theme_create_time
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public Date getThemeCreateTime() {
        return themeCreateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column tb_theme.theme_create_time
     *
     * @param themeCreateTime the value for tb_theme.theme_create_time
     *
     * @mbg.generated Fri Jul 27 14:52:47 CST 2018
     */
    public void setThemeCreateTime(Date themeCreateTime) {
        this.themeCreateTime = themeCreateTime;
    }

    @Override
    public String toString() {
        return "TbTheme{" +
                "themeId=" + themeId +
                ", themeName='" + themeName + '\'' +
                ", themeDetail='" + themeDetail + '\'' +
                ", themeLevel=" + themeLevel +
                ", themeCreateTime=" + themeCreateTime +
                '}';
    }
}